from pygame import USEREVENT

# события переключения окна 0 - 9
START_WINDOW = USEREVENT
LEVEL_SELECTION = USEREVENT + 1
LOADING_WINDOW = USEREVENT + 2
GAME_WINDOW = USEREVENT + 3
SETTINGS_WINDOW = USEREVENT + 4
WIN_WINDOW = USEREVENT + 5
GAME_OVER_WINDOW = USEREVENT + 6

# игровые события 10 - 19
PAUSE = USEREVENT + 10
AI_DESTROYED = USEREVENT + 11
STOP_GAME = USEREVENT + 12
PLAYER_KILLED = USEREVENT + 13
PLAYER_GET_BONUS = USEREVENT + 14
AI_KILL_ALL = USEREVENT + 15
BASE_UPGRADE = USEREVENT + 16
BASE_DEGRADE = USEREVENT + 17

# события включения эффектов или музыки 20 - 29
BACKGROUND_MUSIC_EVENT = USEREVENT + 20
START_EFFECT_EVENT = USEREVENT + 21
TEST_EFFECT_EVENT = USEREVENT + 22
SHOT_EFFECT_EVENT = USEREVENT + 23
READY_EFFECT_EVENT = USEREVENT + 24
VOLUME_UP = USEREVENT + 25
VOLUME_DOWN = USEREVENT + 26
STANDART_VOLUME = USEREVENT + 27
